# Copyright (C) 2019  Adrien Boussicault <adrien.boussicault@labri.fr>
#
# This program is free software: you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation, either
# version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this program.  If not, see
# <http://www.gnu.org/licenses/>.

files_with_terminal_command=$(
  grep -l -r -e "TERMINAL_\(COMMAND\|PARAMETER\)" *|grep -e ".*.c\(pp\)\?$"
)

all_files_without_end_line=""
for i in $files_with_terminal_command
do
  file_with_no_end_line=$(cat $i| awk '{ printf "%s", $0; next}')
  all_files_without_end_line+="${file_with_no_end_line}"
done;

function extract_entries_in_py_format (){
  reg_exp=$1
  out_exp=$2
  matches=$(
    echo $all_files_without_end_line|
    grep -o -e "$reg_exp"
  )
  entries_in_py_format=$(
    echo $matches|
    sed -e "s/$reg_exp/$out_exp/g"|
    awk '{ printf "%s", $0; next}'
  )
  echo "${entries_in_py_format}" 
}

echo "# This file is automatically generated by extract_command.sh" > terminal_command.py

reg_exp="[ \t]*TERMINAL_COMMAND([ \t]*\([^, \t]*\)[ \t]*,[ \t]*\"\([^\"]*\)\"[ \t]*)"
out_exp="('\1', \"\2\"), "
tc_entries=$(extract_entries_in_py_format "${reg_exp}" "${out_exp}")
echo "terminal_command = [${tc_entries}]" >> terminal_command.py

reg_exp="[ \t]*TERMINAL_PARAMETER_INT([ \t]*\([^, \t]*\)[ \t]*,[ \t]*\"\([^\"]*\)\"[ \t]*,"
out_exp="('\1', \"\2\"), "
tc_entries=$(extract_entries_in_py_format "${reg_exp}" "${out_exp}")
echo "parameter_int = [${tc_entries}]" >> terminal_command.py


reg_exp="[ \t]*TERMINAL_PARAMETER_FLOAT([ \t]*\([^, \t]*\)[ \t]*,[ \t]*\"\([^\"]*\)\"[ \t]*,"
out_exp="('\1', \"\2\"), "
tc_entries=$(extract_entries_in_py_format "${reg_exp}" "${out_exp}")
echo "parameter_float = [${tc_entries}]" >> terminal_command.py


reg_exp="[ \t]*TERMINAL_PARAMETER_BOOL([ \t]*\([^, \t]*\)[ \t]*,[ \t]*\"\([^\"]*\)\"[ \t]*,"
out_exp="('\1', \"\2\"), "
tc_entries=$(extract_entries_in_py_format "${reg_exp}" "${out_exp}")
echo "parameter_bool = [${tc_entries}]" >> terminal_command.py


